# Path: .github/workflows/docker-test.yml
name: Docker Test Server CI

on:
  push:
    branches:
      - main

jobs:
  run-docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Test Server
        run: |
          docker compose -f docker-compose-testserver.yml up -d

      - name: Wait for test completion
        run: |
          echo "Waiting for test to complete..."
          timeout 120 docker logs -f server_test || true

      - name: Check test result
        run: |
          if docker logs server_test 2>&1 | grep -q "Success!"; then
            echo "✅ Test PASSED"
            exit 0
          else
            echo "❌ Test FAILED"
            exit 1
          fi
